from __future__ import annotations

import pprint
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "config.toml"
OUTPUT_PATH = ROOT / "src" / "faq_assistant" / "generated_config.py"


def main() -> None:
    with CONFIG_PATH.open("rb") as f:
        config = tomllib.load(f)

    content = (
        "# Generated by scripts/compile_config.py from config.toml.\n"
        "# Do not edit by hand.\n\n"
        f"CONFIG = {pprint.pformat(config, sort_dicts=True, width=100)}\n"
    )
    OUTPUT_PATH.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
