# Generated by scripts/compile_config.py from config.toml.
# Do not edit by hand.

CONFIG = {'answering': {'include_sources': True,
               'max_output_tokens': 1200,
               'max_sources': 5,
               'prompts': {'course': 'You are a DataTalks.Club teaching assistant replying to a '
                                     'student in Slack.\n'
                                     'Answer their question directly and practically, using only '
                                     'the retrieved course\n'
                                     'context. Tell them what to do in your own words - do NOT '
                                     'describe what "the\n'
                                     'context" or "the docs" say. State facts as facts in the '
                                     'active voice: never\n'
                                     'attribute them with "described as", "are described", "said '
                                     'to be", or similar -\n'
                                     'e.g. write "the workshops are hands-on sessions with minimal '
                                     'slides and maximum\n'
                                     'practice", not "they\'re described as hands-on sessions". Be '
                                     'specific: when the context contains a relevant\n'
                                     'link, command, channel name, or exact value, include it '
                                     'directly in the answer as\n'
                                     'a Markdown link or code - never refer to something as '
                                     '"linked there" or "see the\n'
                                     'page" without giving the actual link/value. Keep it concise. '
                                     'If the context does\n'
                                     'not answer the question, set found_answer to false and say '
                                     'you could not find it\n'
                                     'in the course materials. In source_ids, list the ids of the '
                                     'CONTEXT entries you actually used.\n',
                           'docs': 'You are a DataTalks.Club assistant replying to a community '
                                   'member in Slack.\n'
                                   'Answer their question directly and practically, using only the '
                                   'retrieved\n'
                                   'DataTalks.Club documentation. Give the concrete steps in your '
                                   'own words - do NOT\n'
                                   'describe what "the docs" or "the context" say. State facts as '
                                   'facts in the active\n'
                                   'voice: never attribute them with "described as", "are '
                                   'described", "said to be", or\n'
                                   'similar - e.g. write "the workshops are hands-on sessions with '
                                   'minimal slides and\n'
                                   'maximum practice", not "they\'re described as hands-on '
                                   'sessions". Be specific: when the context\n'
                                   'contains a relevant link, command, channel name, or exact '
                                   'value, include it\n'
                                   'directly in the answer as a Markdown link or code - never '
                                   'refer to something as\n'
                                   '"linked there" or "see the page" without giving the actual '
                                   'link/value. Keep it\n'
                                   'concise. If the context does not answer the question, set '
                                   'found_answer to false and\n'
                                   'say you could not find it in the docs. In source_ids, list the '
                                   'ids of the CONTEXT entries you actually used.\n'},
               'temperature': 0.2},
 'api': {'shared_secret_env': 'FAQ_ASSISTANT_SHARED_SECRET'},
 'app': {'environment': 'dev', 'name': 'faq-assistant'},
 'chat': {'model': 'gpt-5.4-mini', 'provider': 'openai', 'rewrite_model': 'gpt-4o-mini'},
 'cloudflare': {'account_id_env': 'CLOUDFLARE_ACCOUNT_ID',
                'api_token_env': 'CLOUDFLARE_API_TOKEN',
                'worker': {'compatibility_date': '2026-06-17',
                           'compatibility_flags': ['python_workers'],
                           'name': 'faq-assistant'}},
 'courses': {'ai-dev-tools-zoomcamp': {'docs_prefix': 'courses/ai-dev-tools-zoomcamp/',
                                       'faq_enabled': True,
                                       'github_repositories': [{'ref': 'main',
                                                                'repo': 'DataTalksClub/ai-dev-tools-zoomcamp'}],
                                       'name': 'AI Dev Tools Zoomcamp',
                                       'slack_channels': ['C09HWT76L95']},
             'data-engineering-zoomcamp': {'docs_prefix': 'courses/data-engineering-zoomcamp/',
                                           'faq_enabled': True,
                                           'github_repositories': [{'ref': 'main',
                                                                    'repo': 'DataTalksClub/data-engineering-zoomcamp'}],
                                           'name': 'Data Engineering Zoomcamp',
                                           'slack_channels': ['C01FABYF2RG']},
             'llm-zoomcamp': {'docs_prefix': 'courses/llm-zoomcamp/',
                              'faq_enabled': True,
                              'github_repositories': [{'ref': 'main',
                                                       'repo': 'DataTalksClub/llm-zoomcamp'}],
                              'name': 'LLM Zoomcamp',
                              'slack_channels': ['C06TEGTGM3J']},
             'machine-learning-zoomcamp': {'docs_prefix': 'courses/ml-zoomcamp/',
                                           'faq_enabled': True,
                                           'github_repositories': [{'ref': 'main',
                                                                    'repo': 'DataTalksClub/machine-learning-zoomcamp'}],
                                           'name': 'Machine Learning Zoomcamp',
                                           'slack_channels': ['C0288NJ5XSA']},
             'mlops-zoomcamp': {'docs_prefix': 'courses/mlops-zoomcamp/',
                                'faq_enabled': True,
                                'github_repositories': [{'ref': 'main',
                                                         'repo': 'DataTalksClub/mlops-zoomcamp'}],
                                'name': 'MLOps Zoomcamp',
                                'slack_channels': ['C02R98X7DS9']},
             'stock-markets-analytics-zoomcamp': {'docs_prefix': 'courses/stock-markets-analytics-zoomcamp/',
                                                  'faq_enabled': True,
                                                  'github_repositories': [{'ref': 'main',
                                                                           'repo': 'DataTalksClub/stock-markets-analytics-zoomcamp'}],
                                                  'name': 'Stock Markets Analytics Zoomcamp',
                                                  'slack_channels': ['C06L1RTF10F']}},
 'ingestion': {'batch_size': 100,
               'chunk': {'max_chars': 1800, 'overlap_chars': 150},
               'github': {'fetch_library': 'gitsource', 'token_env': 'GITHUB_TOKEN'},
               'metadata_text_max_chars': 6000},
 'observability': {'dataset': 'faq_usage',
                   'enabled': True,
                   'prices': {'gpt-4o-mini': {'input': 0.15, 'output': 0.6},
                              'gpt-5.4-mini': {'input': 0.75, 'output': 4.5}}},
 'openai': {'api_key_env': 'OPENAI_API_KEY', 'base_url': 'https://api.openai.com/v1'},
 'retrieval': {'backend': 'zerosearch',
               'boosts': {'section': 1.5, 'text': 1.0, 'title': 3.0},
               'default_limit': 6,
               'max_limit': 10,
               'min_score': 0.2,
               'rewrite_query': True,
               'scopes': {'course': {'filter_fields': {'course': 'required', 'scope': 'course'}},
                          'docs': {'filter_fields': {'scope': 'docs'}}}},
 'slack': {'bot_token_env': 'SLACK_BOT_TOKEN',
           'channels': {'C01FABYF2RG': {'course': 'data-engineering-zoomcamp',
                                        'name': 'course-data-engineering',
                                        'scope': 'course'},
                        'C0288NJ5XSA': {'course': 'machine-learning-zoomcamp',
                                        'name': 'course-ml',
                                        'scope': 'course'},
                        'C02R98X7DS9': {'course': 'mlops-zoomcamp',
                                        'name': 'course-mlops',
                                        'scope': 'course'},
                        'C06L1RTF10F': {'course': 'stock-markets-analytics-zoomcamp',
                                        'name': 'course-stocks-analytics',
                                        'scope': 'course'},
                        'C06TEGTGM3J': {'course': 'llm-zoomcamp',
                                        'name': 'course-llm',
                                        'scope': 'course'},
                        'C09HWT76L95': {'course': 'ai-dev-tools-zoomcamp',
                                        'name': 'course-ai-dev-tools',
                                        'scope': 'course'}},
           'default_scope': 'docs',
           'events_path': '/slack/events',
           'reply': {'thread': True, 'unfurl_links': False, 'unfurl_media': False},
           'signing_secret_env': 'SLACK_SIGNING_SECRET'},
 'sources': {'course_markdown': {'course_definitions': 'courses',
                                 'enabled': True,
                                 'github': {'exclude': ['vendor/**', 'node_modules/**', '.git/**'],
                                            'include': ['*.md', '**/*.md'],
                                            'include_from_course_docs_prefix': True,
                                            'ref': 'main',
                                            'repo': 'DataTalksClub/docs'},
                                 'item_id_prefix': 'course-md',
                                 'scope': 'course'},
             'course_repositories': {'course_definitions': 'courses',
                                     'enabled': True,
                                     'github': {'exclude': ['.git/**',
                                                            'data/**',
                                                            'images/**',
                                                            'notebooks/**',
                                                            'node_modules/**'],
                                                'include': ['README.md',
                                                            'cohorts/**/*.md',
                                                            'certificates.md',
                                                            'project.md',
                                                            'homework.md',
                                                            '**/*.md']},
                                     'item_id_prefix': 'repo',
                                     'scope': 'course'},
             'docs': {'enabled': True,
                      'github': {'exclude': ['courses/**',
                                             'drafts/**',
                                             '.claude/**',
                                             '_sass/**',
                                             'vendor/**',
                                             'node_modules/**',
                                             '.git/**',
                                             'AGENTS.md',
                                             'CLAUDE.md',
                                             'CONTRIBUTING.md',
                                             'README.md',
                                             'example-structure.md'],
                                 'include': ['*.md', '**/*.md'],
                                 'ref': 'main',
                                 'repo': 'DataTalksClub/docs'},
                      'item_id_prefix': 'docs',
                      'scope': 'docs'},
             'faq': {'courses_url': 'https://datatalks.club/faq/json/courses.json',
                     'enabled': True,
                     'item_id_prefix': 'faq'}}}
